version: "3.3"
services:
  whisper:
    build:
      context: ./whisper/
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  speech:
    build:
      context: ./speech/
    stdin_open: true
    tty: true