version: "3.3"
services:
  train-speech:
    build:
      context: .
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    #restart: on-failure